### ISSUE TITLE
Download box includes unhelpful format notes

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb-suggestion-tracker#271]
https://ifdb.org/viewgame?id=aearuuxv83plclpl

The "Download" box includes links to `gblorb` files, with this fine print:

> For all systems. To play, you'll need a glulx interpreter - visit [Brass Lantern](http://brasslantern.org/players/howto/tadownload-d.html) for download links.

But that download link <http://brasslantern.org/players/howto/tadownload-d.html> is broken, and it's not clear what to replace it with unless/until we have a working DL Adviser (#21)

None of this is checked into the code, either. It's all stored in the `filetypes` table in the database.

**Comment by dfabulich** [comment]
There are a lot of bad links here.

<details> <summary>full data from `filetypes` table</summary>

```
MariaDB [ifdb]> select id, externid, extension, fmtname, `desc`, website, fmtclass from filetypes \G
*************************** 1. row ***************************
       id: 1
 externid: executable
extension: .exe
  fmtname: Application
     desc:
  website: NULL
 fmtclass: X
*************************** 2. row ***************************
       id: 2
 externid: hugo
extension: .hex
  fmtname: Hugo
     desc: For all systems. To play, you'll need a Hugo interpreter - visit the <a href="http://ifwiki.org/index.php/Hugor">Hugor page on ifwiki.org</a> for download links.
  website: NULL
 fmtclass: G
*************************** 3. row ***************************
       id: 3
 externid: tads2
extension: .gam
  fmtname: TADS 2
     desc: For all systems. To play, you'll need a TADS 2 Interpreter - visit <a href="http://www.tads.org/tads2.htm">tads.org</a> for interpreter downloads.
  website: http://www.tads.org/tads2.htm
 fmtclass: G
*************************** 4. row ***************************
       id: 6
 externid: zcode
extension: .z3 .z4 .z5 .z6 .z7 .z8
  fmtname: Z-Machine
     desc: For all systems. To play, you'll need a Z-Machine Interpreter - visit <a href="http://brasslantern.org/players/howto/tadownload-c.html">Brass Lantern</a> for download links.
  website: NULL
 fmtclass: G
*************************** 5. row ***************************
       id: 10
 externid: text
extension: .txt
  fmtname: Text
     desc:
  website: NULL
 fmtclass: NULL
*************************** 6. row ***************************
       id: 4
 externid: tads3
extension: .t3
  fmtname: TADS 3
     desc: For all systems. To play, you'll need a TADS 3 Interpreter - visit <a href="http://www.tads.org/tads3.htm">tads.org</a> for interpreter downloads.
  website: http://www.tads.org/tads3.htm
 fmtclass: G
*************************** 7. row ***************************
       id: 12
 externid: alan2
extension: .acd
  fmtname: Alan 2
     desc: For all systems. To play, you'll need an Alan Interpreter for your system - visit the <a href="http://www.alanif.se">Alan home page</a> for download links.
  website: NULL
 fmtclass: G
*************************** 8. row ***************************
       id: 13
 externid: blorb/zcode
extension: .zblorb .zlb
  fmtname: Z Machine/Blorb
     desc: For all systems. To play, you'll need a Z-Machine Interpreter with Blorb support - visit <a href="http://brasslantern.org/players/howto/tadownload-c.html">Brass Lantern</a> for download links.
  website: NULL
 fmtclass: G
*************************** 9. row ***************************
       id: 21
 externid: pdf
extension: .pdf
  fmtname: PDF
     desc: To view this file, you need an <a href="http://www.adobe.com/products/acrobat/readstep2.html">Acrobat Reader</a> for your system.
  website: http://www.adobe.com/products/acrobat/readstep2.html
 fmtclass: NULL
*************************** 10. row ***************************
       id: 17
 externid: zip
extension: .zip
  fmtname: ZIP
     desc: Compressed with ZIP. Free Unzip tools are available for most systems at <a href="http://www.info-zip.org">www.info-zip.org</a>.
  website: NULL
 fmtclass: Z
*************************** 11. row ***************************
       id: 18
 externid: lha
extension: .lha
  fmtname: LHA
     desc: Compressed with LHA (also known as LHArc). Free unpacking tools are available for most platforms.
  website: NULL
 fmtclass: Z
*************************** 12. row ***************************
       id: 19
 externid: stuffit
extension: .sit
  fmtname: StuffIt
     desc: Compressed with StuffIt. Free StuffIt Expanders are available for most systems at <a href="http://www.stuffit.com">www.stuffit.com</a>.
  website: NULL
 fmtclass: Z
*************************** 13. row ***************************
       id: 20
 externid: document
extension: NULL
  fmtname: Document
     desc:
  website: NULL
 fmtclass: NULL
*************************** 14. row ***************************
       id: 22
 externid: tar.Z
extension: .tar.Z
  fmtname: Tarball (.tar.Z)
     desc: Compressed with the Unix-style .tar.Z <a href="http://en.wikipedia.org/wiki/Tar_(file_format)">"tarball" format</a>. Free unpacking tools are available for most platforms.
  website: NULL
 fmtclass: Z
*************************** 15. row ***************************
       id: 23
 externid: tar.gz
extension: .tar.gz .tgz
  fmtname: Tarball (.tar.gz)
     desc: Compressed with the Unix-style .tar.gz <a href="http://en.wikipedia.org/wiki/Tar_(file_format)">"tarball" format</a>. Free unpacking tools are available for most platforms.
  website: NULL
 fmtclass: Z
*************************** 16. row ***************************
       id: 24
 externid: alan3
extension: NULL
  fmtname: Alan 3
     desc: For all systems. To play, you'll need an Alan Interpreter for your system - visit the <a href="http://www.alanif.se">Alan home page</a> for download links.
  website: http://www.alanif.se
 fmtclass: G
*************************** 17. row ***************************
       id: 25
 externid: glulx
extension: .ulx
  fmtname: Glulx
     desc: For all systems. To play, you'll need a glulx interpreter - visit <a href="http://brasslantern.org/players/howto/tadownload-d.html">Brass Lantern</a> for download links.
  website: NULL
 fmtclass: G
*************************** 18. row ***************************
       id: 26
 externid: agt
extension: .agx
  fmtname: AGT
     desc: Requires an AGT interpreter - see <a href="http://www.brasslantern.org/players/howto/tadownload-c.html">Brass Lantern</a> for download links.
  website: NULL
 fmtclass: G
*************************** 19. row ***************************
       id: 27
 externid: adrift
extension: .taf
  fmtname: ADRIFT 4
     desc: Requires an ADRIFT version 4 interpreter. Visit the <a href="http://www.adrift.org.uk/">ADRIFT site</a> for download links.
  website: http://www.adrift.org.uk/
 fmtclass: G
*************************** 20. row ***************************
       id: 28
 externid: advsys
extension: .dat
  fmtname: AdvSys
     desc: Requires an AdvSys interpreter. (This is an older format that is no longer supported.)
  website: NULL
 fmtclass: G
*************************** 21. row ***************************
       id: 29
 externid: blorb/glulx
extension: .blb .gblorb
  fmtname: Glulx/Blorb
     desc: For all systems. To play, you'll need a glulx interpreter - visit <a href="http://brasslantern.org/players/howto/tadownload-d.html">Brass Lantern</a> for download links.
  website: NULL
 fmtclass: G
*************************** 22. row ***************************
       id: 30
 externid: sit.hqx
extension: .sit.hqx
  fmtname: StuffIt/BinHex
     desc: Compressed with StuffIt, encoded in BinHex format. Free StuffIt Expanders are available for most systems at <a href="http://www.stuffit.com">www.stuffit.com</a>.
  website: www.stuffit.com
 fmtclass: Z
*************************** 23. row ***************************
       id: 31
 externid: guemap
extension: .gmp
  fmtname: GUEmap
     desc: GUEmap file. Requires the GUEmap viewer - visit <a href="http://www.cjmweb.net/GUEmap/">http://www.cjmweb.net/GUEmap</a> for information.
  website: http://www.cjmweb.net/GUEmap/
 fmtclass: NULL
*************************** 24. row ***************************
       id: 32
 externid: jpeg
extension: .jpg .jpe .jpeg
  fmtname: Image (JPEG)
     desc:
  website: NULL
 fmtclass: NULL
*************************** 25. row ***************************
       id: 33
 externid: gif
extension: .gif
  fmtname: Image (GIF)
     desc:
  website: NULL
 fmtclass: NULL
*************************** 26. row ***************************
       id: 34
 externid: png
extension: .png
  fmtname: Image (PNG)
     desc:
  website: NULL
 fmtclass: NULL
*************************** 27. row ***************************
       id: 35
 externid: html
extension: .htm .html
  fmtname: HTML Document
     desc:
  website: NULL
 fmtclass: NULL
*************************** 28. row ***************************
       id: 36
 externid: sit.bin
extension: .sit.bin
  fmtname: StuffIt/MacBinary
     desc: Compressed with StuffIt, encoded in MacBinary format. Free StuffIt Expanders are available for most systems at <a href="http://www.stuffit.com">www.stuffit.com</a>.
  website: NULL
 fmtclass: NULL
*************************** 29. row ***************************
       id: 37
 externid: setup
extension: NULL
  fmtname: Installer
     desc:
  website: NULL
 fmtclass: X
*************************** 30. row ***************************
       id: 38
 externid: storyfile
extension: NULL
  fmtname: Story File
     desc: This game requires an interpreter program - refer to the game's documentation for details.
  website: NULL
 fmtclass: G
*************************** 31. row ***************************
       id: 39
 externid: bin/hex
extension: .hqx
  fmtname: Bin/Hex
     desc: Encoded in Macintosh <a hfef="http://en.wikipedia.org/wiki/BinHex">Bin/Hex format</a>.
  website: NULL
 fmtclass: Z
*************************** 32. row ***************************
       id: 40
 externid: gzip
extension: .gz
  fmtname: gzip
     desc: Compressed with gzip. Free unpacking tools are available for most systems.
  website: NULL
 fmtclass: Z
*************************** 33. row ***************************
       id: 41
 externid: tar
extension: .tar
  fmtname: tar
     desc: Stored in Unix "tar" format. Free unpacking tools are available for most systems.
  website: NULL
 fmtclass: Z
*************************** 34. row ***************************
       id: 42
 externid: MacBinary
extension: .bin
  fmtname: MacBinary
     desc: MacBinary format. Files in this format are primarily for MacOS use.
  website: NULL
 fmtclass: Z
*************************** 35. row ***************************
       id: 43
 externid: *
extension: NULL
  fmtname: All Formats
     desc: This is a pseudo-format used to represent download adviser records that apply to multiple formats.
  website: NULL
 fmtclass: NULL
*************************** 36. row ***************************
       id: 44
 externid: adrift39
extension: .taf
  fmtname: ADRIFT 3.9
     desc: Requires an ADRIFT version 3.9 interpreter. Visit the <a href="http://www.adrift.org.uk/">ADRIFT site</a> for download links.
  website: http://www.adrift.org.uk/
 fmtclass: G
*************************** 37. row ***************************
       id: 45
 externid: adrift38
extension: .taf
  fmtname: ADRIFT 3.8
     desc: Requires an ADRIFT version 3.8 interpreter. Visit the <a href="http://www.adrift.org.uk/">ADRIFT site</a> for download links.
  website: http://www.adrift.org.uk/
 fmtclass: G
*************************** 38. row ***************************
       id: 46
 externid: rar
extension: .rar
  fmtname: RAR
     desc: Compressed with RAR. Unpacking tools are available for most platforms - see <a href="http://en.wikipedia.org/wiki/RAR">Wikipedia</a> for pointers.
  website: http://www.rarlab.com
 fmtclass: Z
*************************** 39. row ***************************
       id: 47
 externid: compressed-other
extension: NULL
  fmtname: Other Compression Format
     desc: This is a compressed file.
  website: NULL
 fmtclass: Z
*************************** 40. row ***************************
       id: 48
 externid: adrift5
extension: NULL
  fmtname: ADRIFT 5
     desc: Requires an ADRIFT version 5 interpreter.  Visit the <a href="http://www.adrift.org.uk/">ADRIFT site</a> for download links.
  website: http://www.adrift.org.uk/
 fmtclass: G
*************************** 41. row ***************************
       id: 49
 externid: adrift5/blorb
extension: NULL
  fmtname: ADRIFT 5/Blorb
     desc: Requires an ADRIFT version 5 interpreter. Visit the <a href="http://www.adrift.org.uk/">ADRIFT site</a> for download links.
  website: http://www.adrift.org.uk/
 fmtclass: G
*************************** 42. row ***************************
       id: 50
 externid: tads3web
extension: NULL
  fmtname: TADS 3 Web
     desc: Play on the Internet with a browser, or download for use with a TADS Web UI-compatible interpreter - visit <a href="http://www.tads.org">www.tads.org</a> for interpreter downloads.
  website: http://www.tads.org/tads3.htm
 fmtclass: G
*************************** 43. row ***************************
       id: 53
 externid: hypertextgame
extension: .htm .html
  fmtname: Hypertext (HTML)
     desc: Play this game in your Web browser.
  website: NULL
 fmtclass: G
43 rows in set (0.001 sec)
```

</details>
